import {
  calculateSettlement,
  canHostBook,
  cents,
  getMoneySafetySnapshot,
  type AuditEvent,
  type HostReimbursement,
  type ProcessedStripeWebhookEvent,
  type ProtectedPod,
  type ProtectedPodMember,
  type ProtectedUser,
  type RidePodPaymentIntent,
  type RiskFlag,
  type Settlement,
} from "@/lib/money-safety";

const now = "2026-05-13T12:00:00.000Z";

export const protectedUsers: ProtectedUser[] = [
  {
    id: "u1",
    name: "Maya Chen",
    email: "maya@example.com",
    phone: "+12135550101",
    genderIdentity: "FEMALE",
    genderVerifiedAt: "2024-09-01T10:00:00.000Z",
    verificationStatus: "ID_VERIFIED",
    communityId: "usc",
    trustScore: 4.9,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 0,
    riskStatus: "NORMAL",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u2",
    name: "Andre Lee",
    email: "andre@example.com",
    phone: "+12135550102",
    genderIdentity: "MALE",
    genderVerifiedAt: "2024-09-01T10:00:00.000Z",
    verificationStatus: "PHONE_VERIFIED",
    communityId: "usc",
    trustScore: 4.6,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 0,
    riskStatus: "NORMAL",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u3",
    name: "Priya Shah",
    email: "priya@example.com",
    phone: "+12135550103",
    genderIdentity: "FEMALE",
    genderVerifiedAt: null,
    verificationStatus: "EMAIL_VERIFIED",
    communityId: "usc",
    trustScore: 4.4,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 0,
    riskStatus: "NORMAL",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u4",
    name: "Sam Rivera",
    email: "sam@example.com",
    phone: "+12135550104",
    genderIdentity: "FEMALE",
    genderVerifiedAt: "2024-09-01T10:00:00.000Z",
    verificationStatus: "ID_VERIFIED",
    communityId: "ucb",
    trustScore: 4.9,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 0,
    riskStatus: "NORMAL",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u5",
    name: "Nora Patel",
    email: "nora@example.com",
    phone: "+12135550105",
    genderIdentity: "FEMALE",
    genderVerifiedAt: "2024-09-01T10:00:00.000Z",
    verificationStatus: "ID_VERIFIED",
    communityId: "ucb",
    trustScore: 4.7,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 0,
    riskStatus: "NORMAL",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u6",
    name: "Jordan Lee",
    email: "jordan@example.com",
    phone: "+12135550106",
    genderIdentity: "NON_BINARY",
    genderVerifiedAt: "2024-09-01T10:00:00.000Z",
    verificationStatus: "COMMUNITY_VERIFIED",
    communityId: "usc",
    trustScore: 4.8,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 0,
    riskStatus: "NORMAL",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u7",
    name: "Alex Kim",
    email: "alex@example.com",
    phone: "+12135550107",
    genderIdentity: "PREFER_NOT_TO_SAY",
    genderVerifiedAt: null,
    verificationStatus: "PHONE_VERIFIED",
    communityId: "usc",
    trustScore: 4.7,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 0,
    riskStatus: "NORMAL",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "low-trust",
    name: "Low Trust Rider",
    email: "low@example.com",
    phone: "+12135550108",
    genderIdentity: "FEMALE",
    genderVerifiedAt: "2024-09-01T10:00:00.000Z",
    verificationStatus: "PHONE_VERIFIED",
    communityId: "usc",
    trustScore: 3.9,
    noShowCount: 1,
    lateCancelCount: 1,
    safetyReportCount: 0,
    riskStatus: "WATCH",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "unknown-gender",
    name: "Unknown Gender Rider",
    email: "unknown@example.com",
    phone: "+12135550109",
    genderIdentity: "UNKNOWN",
    genderVerifiedAt: null,
    verificationStatus: "PHONE_VERIFIED",
    communityId: "usc",
    trustScore: 4.7,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 0,
    riskStatus: "NORMAL",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "wrong-community",
    name: "Wrong Community Rider",
    email: "wrong-community@example.com",
    phone: "+12135550110",
    genderIdentity: "FEMALE",
    genderVerifiedAt: "2024-09-01T10:00:00.000Z",
    verificationStatus: "COMMUNITY_VERIFIED",
    communityId: "other",
    trustScore: 4.8,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 0,
    riskStatus: "NORMAL",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "suspended",
    name: "Suspended Rider",
    email: "suspended@example.com",
    phone: "+12135550111",
    genderIdentity: "FEMALE",
    genderVerifiedAt: "2024-09-01T10:00:00.000Z",
    verificationStatus: "ID_VERIFIED",
    communityId: "usc",
    trustScore: 4.9,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 2,
    riskStatus: "SUSPENDED",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
];

function member(
  userId: string,
  role: ProtectedPodMember["role"],
  overrides: Partial<ProtectedPodMember> = {},
): ProtectedPodMember {
  return {
    id: `pm-usc-lax-001-${userId}`,
    podId: "usc-lax-001",
    userId,
    role,
    memberState: "CONFIRMED",
    paymentState: "AUTHORIZED",
    seatCount: 1,
    maxChargeCents: cents(24.5),
    estimatedShareCents: cents(18.5),
    finalChargeCents: null,
    platformFeeCents: cents(2),
    cancellationLiabilityCents: null,
    noShowLiabilityCents: null,
    joinedAt: "2026-05-11T10:00:00.000Z",
    lockedAt: "2026-05-13T02:00:00.000Z",
    canceledAt: null,
    cancelReason: null,
    checkinState: "NOT_CHECKED_IN",
    trustDelta: null,
    eligibilityPassed: true,
    createdAt: "2026-05-11T10:00:00.000Z",
    updatedAt: now,
    ...overrides,
  };
}

export const protectedPods: ProtectedPod[] = [
  {
    id: "usc-lax-001",
    hostUserId: "u1",
    lifecycleState: "HOST_CAN_BOOK",
    bookingState: "CAN_BOOK",
    genderMode: "MIXED",
    accessMode: "VERIFIED_ONLY",
    inviteCode: "USC-LAX-MAY14",
    communityId: "usc",
    minTrustScore: null,
    originGeneral: "USC",
    destinationGeneral: "LAX",
    pickupDetail: "USC - Leavey Library rideshare pickup zone",
    dropoffDetail: "LAX - Terminal 1 departures level",
    departureAt: "2026-05-14T07:30:00.000-07:00",
    departureWindowMinutes: 15,
    targetSeats: 4,
    minSeatsToBook: 3,
    maxSeats: 4,
    estimatedTotalFareCents: cents(74),
    approvedMaxTotalFareCents: cents(90),
    currency: "USD",
    ridepodFeeCents: cents(2),
    providerPolicy: "Host books under approved max fare. Everyone pays their share.",
    cancellationPolicyId: "standard-airport",
    lockDeadlineAt: "2026-05-13T20:00:00.000-07:00",
    bookingDeadlineAt: "2026-05-14T07:00:00.000-07:00",
    chatUnlockedAt: "2026-05-13T20:02:00.000-07:00",
    detailsUnlockedAt: "2026-05-13T20:02:00.000-07:00",
    hostReplacementStartedAt: null,
    originalHostUserId: null,
    replacementHostUserId: null,
    members: [member("u1", "HOST"), member("u6", "RIDER"), member("u7", "RIDER")],
    quotes: [
      {
        id: "quote-usc-lax-001-1",
        podId: "usc-lax-001",
        hostUserId: "u1",
        providerName: "UBER",
        vehicleClass: "Large Ride",
        quotedFareCents: cents(82.4),
        currency: "USD",
        routeSummary: "USC to LAX",
        screenshotFileUrl: "mock://quote/usc-lax-001.png",
        screenshotFileId: "mock-file-quote-usc-lax-001",
        submittedAt: "2026-05-13T19:45:00.000-07:00",
        reviewState: "AUTO_APPROVED",
        reviewedByAdminId: null,
        adminNotes: null,
        isFresh: true,
        expiresAt: "2026-05-14T07:00:00.000-07:00",
      },
    ],
    receipts: [],
    adminReviewRequired: false,
    higherMaxApprovedCents: null,
    createdAt: "2026-05-11T10:00:00.000Z",
    updatedAt: now,
  },
  {
    id: "women-only-demo",
    hostUserId: "u1",
    lifecycleState: "FORMING",
    bookingState: "QUOTE_ALLOWED",
    genderMode: "WOMEN_ONLY",
    accessMode: "VERIFIED_ONLY",
    inviteCode: null,
    communityId: "usc",
    minTrustScore: null,
    originGeneral: "USC",
    destinationGeneral: "LAX",
    pickupDetail: null,
    dropoffDetail: null,
    departureAt: "2026-05-14T20:30:00.000-07:00",
    departureWindowMinutes: 10,
    targetSeats: 3,
    minSeatsToBook: 2,
    maxSeats: 3,
    estimatedTotalFareCents: cents(60),
    approvedMaxTotalFareCents: cents(75),
    currency: "USD",
    ridepodFeeCents: cents(2),
    providerPolicy: null,
    cancellationPolicyId: "standard",
    lockDeadlineAt: null,
    bookingDeadlineAt: null,
    chatUnlockedAt: null,
    detailsUnlockedAt: null,
    hostReplacementStartedAt: null,
    originalHostUserId: null,
    replacementHostUserId: null,
    members: [member("u1", "HOST", { podId: "women-only-demo", id: "pm-women-only-demo-u1" })],
    quotes: [],
    receipts: [],
    adminReviewRequired: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "mixed-open-demo",
    hostUserId: "u1",
    lifecycleState: "FORMING",
    bookingState: "QUOTE_ALLOWED",
    genderMode: "MIXED",
    accessMode: "OPEN",
    inviteCode: null,
    communityId: null,
    minTrustScore: null,
    originGeneral: "Downtown",
    destinationGeneral: "Airport",
    pickupDetail: null,
    dropoffDetail: null,
    departureAt: "2026-05-15T08:00:00.000-07:00",
    departureWindowMinutes: 15,
    targetSeats: 4,
    minSeatsToBook: 2,
    maxSeats: 4,
    estimatedTotalFareCents: cents(80),
    approvedMaxTotalFareCents: cents(96),
    currency: "USD",
    ridepodFeeCents: cents(2),
    providerPolicy: null,
    cancellationPolicyId: "standard",
    lockDeadlineAt: null,
    bookingDeadlineAt: null,
    chatUnlockedAt: null,
    detailsUnlockedAt: null,
    hostReplacementStartedAt: null,
    originalHostUserId: null,
    replacementHostUserId: null,
    members: [member("u1", "HOST", { podId: "mixed-open-demo", id: "pm-mixed-open-demo-u1" })],
    quotes: [],
    receipts: [],
    adminReviewRequired: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "community-only-demo",
    hostUserId: "u1",
    lifecycleState: "FORMING",
    bookingState: "QUOTE_ALLOWED",
    genderMode: "MIXED",
    accessMode: "COMMUNITY_ONLY",
    inviteCode: null,
    communityId: "usc",
    minTrustScore: null,
    originGeneral: "USC",
    destinationGeneral: "LAX",
    pickupDetail: null,
    dropoffDetail: null,
    departureAt: "2026-05-16T08:00:00.000-07:00",
    departureWindowMinutes: 15,
    targetSeats: 4,
    minSeatsToBook: 2,
    maxSeats: 4,
    estimatedTotalFareCents: cents(80),
    approvedMaxTotalFareCents: cents(96),
    currency: "USD",
    ridepodFeeCents: cents(2),
    providerPolicy: null,
    cancellationPolicyId: "standard",
    lockDeadlineAt: null,
    bookingDeadlineAt: null,
    chatUnlockedAt: null,
    detailsUnlockedAt: null,
    hostReplacementStartedAt: null,
    originalHostUserId: null,
    replacementHostUserId: null,
    members: [member("u1", "HOST", { podId: "community-only-demo", id: "pm-community-only-demo-u1" })],
    quotes: [],
    receipts: [],
    adminReviewRequired: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "high-trust-demo",
    hostUserId: "u1",
    lifecycleState: "FORMING",
    bookingState: "QUOTE_ALLOWED",
    genderMode: "MIXED",
    accessMode: "HIGH_TRUST_ONLY",
    inviteCode: null,
    communityId: null,
    minTrustScore: 4.5,
    originGeneral: "USC",
    destinationGeneral: "LAX",
    pickupDetail: null,
    dropoffDetail: null,
    departureAt: "2026-05-17T08:00:00.000-07:00",
    departureWindowMinutes: 15,
    targetSeats: 4,
    minSeatsToBook: 2,
    maxSeats: 4,
    estimatedTotalFareCents: cents(80),
    approvedMaxTotalFareCents: cents(96),
    currency: "USD",
    ridepodFeeCents: cents(2),
    providerPolicy: null,
    cancellationPolicyId: "standard",
    lockDeadlineAt: null,
    bookingDeadlineAt: null,
    chatUnlockedAt: null,
    detailsUnlockedAt: null,
    hostReplacementStartedAt: null,
    originalHostUserId: null,
    replacementHostUserId: null,
    members: [member("u1", "HOST", { podId: "high-trust-demo", id: "pm-high-trust-demo-u1" })],
    quotes: [],
    receipts: [],
    adminReviewRequired: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "invite-only-demo",
    hostUserId: "u1",
    lifecycleState: "FORMING",
    bookingState: "QUOTE_ALLOWED",
    genderMode: "MIXED",
    accessMode: "INVITE_ONLY",
    inviteCode: "INVITE-123",
    communityId: null,
    minTrustScore: null,
    originGeneral: "USC",
    destinationGeneral: "LAX",
    pickupDetail: null,
    dropoffDetail: null,
    departureAt: "2026-05-18T08:00:00.000-07:00",
    departureWindowMinutes: 15,
    targetSeats: 4,
    minSeatsToBook: 2,
    maxSeats: 4,
    estimatedTotalFareCents: cents(80),
    approvedMaxTotalFareCents: cents(96),
    currency: "USD",
    ridepodFeeCents: cents(2),
    providerPolicy: null,
    cancellationPolicyId: "standard",
    lockDeadlineAt: null,
    bookingDeadlineAt: null,
    chatUnlockedAt: null,
    detailsUnlockedAt: null,
    hostReplacementStartedAt: null,
    originalHostUserId: null,
    replacementHostUserId: null,
    members: [member("u1", "HOST", { podId: "invite-only-demo", id: "pm-invite-only-demo-u1" })],
    quotes: [],
    receipts: [],
    adminReviewRequired: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "airport-sfo-721",
    hostUserId: "u1",
    lifecycleState: "PAYMENT_LOCKING",
    bookingState: "QUOTE_ALLOWED",
    genderMode: "MIXED",
    accessMode: "VERIFIED_ONLY",
    inviteCode: null,
    communityId: null,
    minTrustScore: null,
    originGeneral: "Mission District",
    destinationGeneral: "SFO",
    pickupDetail: null,
    dropoffDetail: null,
    departureAt: "2026-05-18T05:45:00.000-07:00",
    departureWindowMinutes: 10,
    targetSeats: 4,
    minSeatsToBook: 3,
    maxSeats: 4,
    estimatedTotalFareCents: cents(74),
    approvedMaxTotalFareCents: cents(92),
    currency: "USD",
    ridepodFeeCents: cents(2),
    providerPolicy: null,
    cancellationPolicyId: "standard",
    lockDeadlineAt: "2026-05-17T20:00:00.000-07:00",
    bookingDeadlineAt: "2026-05-18T05:10:00.000-07:00",
    chatUnlockedAt: null,
    detailsUnlockedAt: null,
    hostReplacementStartedAt: null,
    originalHostUserId: null,
    replacementHostUserId: null,
    members: [
      member("u1", "HOST", { podId: "airport-sfo-721", id: "pm-airport-sfo-721-u1" }),
      member("u2", "RIDER", { podId: "airport-sfo-721", id: "pm-airport-sfo-721-u2" }),
      member("u4", "RIDER", {
        podId: "airport-sfo-721",
        id: "pm-airport-sfo-721-u4",
        memberState: "PAYMENT_REQUIRED",
        paymentState: "PAYMENT_METHOD_REQUIRED",
        lockedAt: null,
      }),
    ],
    quotes: [],
    receipts: [],
    adminReviewRequired: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "locked-no-quote-demo",
    hostUserId: "u1",
    lifecycleState: "LOCKED",
    bookingState: "QUOTE_ALLOWED",
    genderMode: "MIXED",
    accessMode: "OPEN",
    inviteCode: null,
    communityId: null,
    minTrustScore: null,
    originGeneral: "Downtown",
    destinationGeneral: "Airport",
    pickupDetail: "Grand Ave hotel loop",
    dropoffDetail: "Departures level, Door 4",
    departureAt: "2026-05-20T07:40:00.000-07:00",
    departureWindowMinutes: 5,
    targetSeats: 4,
    minSeatsToBook: 3,
    maxSeats: 4,
    estimatedTotalFareCents: cents(57),
    approvedMaxTotalFareCents: cents(72),
    currency: "USD",
    ridepodFeeCents: cents(2),
    providerPolicy: null,
    cancellationPolicyId: "standard",
    lockDeadlineAt: "2026-05-19T20:00:00.000-07:00",
    bookingDeadlineAt: "2026-05-20T07:10:00.000-07:00",
    chatUnlockedAt: "2026-05-19T20:05:00.000-07:00",
    detailsUnlockedAt: "2026-05-19T20:05:00.000-07:00",
    hostReplacementStartedAt: null,
    originalHostUserId: null,
    replacementHostUserId: null,
    members: [
      member("u1", "HOST", { podId: "locked-no-quote-demo", id: "pm-locked-no-quote-demo-u1" }),
      member("u2", "RIDER", { podId: "locked-no-quote-demo", id: "pm-locked-no-quote-demo-u2" }),
      member("u4", "RIDER", { podId: "locked-no-quote-demo", id: "pm-locked-no-quote-demo-u4" }),
    ],
    quotes: [],
    receipts: [],
    adminReviewRequired: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "campus-commute-442",
    hostUserId: "u4",
    lifecycleState: "LOCKED",
    bookingState: "QUOTE_SUBMITTED",
    genderMode: "WOMEN_ONLY",
    accessMode: "COMMUNITY_ONLY",
    inviteCode: null,
    communityId: "usc",
    minTrustScore: null,
    originGeneral: "North Berkeley",
    destinationGeneral: "UC Berkeley",
    pickupDetail: "Monterey Market",
    dropoffDetail: "Bancroft Gate",
    departureAt: "2026-05-25T08:10:00.000-07:00",
    departureWindowMinutes: 5,
    targetSeats: 4,
    minSeatsToBook: 3,
    maxSeats: 4,
    estimatedTotalFareCents: cents(28),
    approvedMaxTotalFareCents: cents(34),
    currency: "USD",
    ridepodFeeCents: cents(1),
    providerPolicy: null,
    cancellationPolicyId: "standard",
    lockDeadlineAt: "2026-05-22T17:00:00.000-07:00",
    bookingDeadlineAt: "2026-05-25T07:45:00.000-07:00",
    chatUnlockedAt: "2026-05-22T17:05:00.000-07:00",
    detailsUnlockedAt: "2026-05-22T17:05:00.000-07:00",
    hostReplacementStartedAt: null,
    originalHostUserId: null,
    replacementHostUserId: null,
    members: [
      member("u4", "HOST", { podId: "campus-commute-442", id: "pm-campus-commute-442-u4" }),
      member("u1", "RIDER", { podId: "campus-commute-442", id: "pm-campus-commute-442-u1" }),
      member("u3", "RIDER", { podId: "campus-commute-442", id: "pm-campus-commute-442-u3" }),
      member("u5", "RIDER", { podId: "campus-commute-442", id: "pm-campus-commute-442-u5" }),
    ],
    quotes: [
      {
        id: "quote-campus-commute-442-1",
        podId: "campus-commute-442",
        hostUserId: "u4",
        providerName: "LYFT",
        vehicleClass: "Standard",
        quotedFareCents: cents(42),
        currency: "USD",
        routeSummary: "North Berkeley to UC Berkeley",
        screenshotFileUrl: "mock://quote/campus-commute-above-max.png",
        screenshotFileId: "mock-file-campus-above-max",
        submittedAt: now,
        reviewState: "NEEDS_APPROVAL",
        reviewedByAdminId: null,
        adminNotes: "Quote is above approved max.",
        isFresh: true,
        expiresAt: null,
      },
    ],
    receipts: [],
    adminReviewRequired: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "host-replacement-demo",
    hostUserId: "u2",
    lifecycleState: "HOST_REPLACEMENT_NEEDED",
    bookingState: "CANCELED_BY_HOST",
    genderMode: "MIXED",
    accessMode: "VERIFIED_ONLY",
    inviteCode: null,
    communityId: null,
    minTrustScore: null,
    originGeneral: "UCLA",
    destinationGeneral: "Burbank Airport",
    pickupDetail: null,
    dropoffDetail: null,
    departureAt: "2026-05-26T09:20:00.000-07:00",
    departureWindowMinutes: 15,
    targetSeats: 4,
    minSeatsToBook: 2,
    maxSeats: 4,
    estimatedTotalFareCents: cents(62),
    approvedMaxTotalFareCents: cents(78),
    currency: "USD",
    ridepodFeeCents: cents(2),
    providerPolicy: null,
    cancellationPolicyId: "standard",
    lockDeadlineAt: "2026-05-25T20:00:00.000-07:00",
    bookingDeadlineAt: "2026-05-26T08:50:00.000-07:00",
    chatUnlockedAt: "2026-05-25T20:05:00.000-07:00",
    detailsUnlockedAt: null,
    hostReplacementStartedAt: now,
    originalHostUserId: "u2",
    replacementHostUserId: null,
    members: [
      member("u2", "HOST", {
        podId: "host-replacement-demo",
        id: "pm-host-replacement-demo-u2",
        memberState: "CANCELED",
        paymentState: "REFUNDED",
        canceledAt: now,
        cancelReason: "Host canceled before booking.",
      }),
      member("u1", "RIDER", { podId: "host-replacement-demo", id: "pm-host-replacement-demo-u1" }),
      member("u6", "RIDER", { podId: "host-replacement-demo", id: "pm-host-replacement-demo-u6" }),
    ],
    quotes: [],
    receipts: [],
    adminReviewRequired: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "private-car-napa-906",
    hostUserId: "u3",
    lifecycleState: "RIDE_BOOKED",
    bookingState: "BOOKED",
    genderMode: "MIXED",
    accessMode: "INVITE_ONLY",
    inviteCode: "NAPA-RETURN",
    communityId: null,
    minTrustScore: null,
    originGeneral: "Downtown Napa",
    destinationGeneral: "San Francisco",
    pickupDetail: "Oxbow Public Market",
    dropoffDetail: "Ferry Building",
    departureAt: "2026-06-06T18:30:00.000-07:00",
    departureWindowMinutes: 15,
    targetSeats: 5,
    minSeatsToBook: 4,
    maxSeats: 5,
    estimatedTotalFareCents: cents(148),
    approvedMaxTotalFareCents: cents(180),
    currency: "USD",
    ridepodFeeCents: cents(3),
    providerPolicy: null,
    cancellationPolicyId: "standard",
    lockDeadlineAt: "2026-06-05T20:00:00.000-07:00",
    bookingDeadlineAt: "2026-06-06T18:00:00.000-07:00",
    chatUnlockedAt: "2026-06-05T20:05:00.000-07:00",
    detailsUnlockedAt: "2026-06-05T20:05:00.000-07:00",
    hostReplacementStartedAt: null,
    originalHostUserId: null,
    replacementHostUserId: null,
    members: [
      member("u3", "HOST", { podId: "private-car-napa-906", id: "pm-private-car-napa-906-u3" }),
      member("u1", "RIDER", { podId: "private-car-napa-906", id: "pm-private-car-napa-906-u1" }),
      member("u2", "RIDER", { podId: "private-car-napa-906", id: "pm-private-car-napa-906-u2" }),
      member("u4", "RIDER", { podId: "private-car-napa-906", id: "pm-private-car-napa-906-u4" }),
      member("u5", "RIDER", { podId: "private-car-napa-906", id: "pm-private-car-napa-906-u5" }),
    ],
    quotes: [
      {
        id: "quote-private-car-napa-906-1",
        podId: "private-car-napa-906",
        hostUserId: "u3",
        providerName: "PRIVATE_VAN",
        vehicleClass: "Private van",
        quotedFareCents: cents(160),
        currency: "USD",
        routeSummary: "Downtown Napa to San Francisco",
        screenshotFileUrl: "mock://quote/private-car-napa-906.png",
        screenshotFileId: "mock-file-napa-quote",
        submittedAt: now,
        reviewState: "AUTO_APPROVED",
        reviewedByAdminId: null,
        adminNotes: null,
        isFresh: true,
        expiresAt: null,
      },
    ],
    receipts: [],
    adminReviewRequired: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "settlement-complete-demo",
    hostUserId: "u1",
    lifecycleState: "SETTLED",
    bookingState: "COMPLETED",
    genderMode: "MIXED",
    accessMode: "VERIFIED_ONLY",
    inviteCode: null,
    communityId: null,
    minTrustScore: null,
    originGeneral: "USC",
    destinationGeneral: "LAX",
    pickupDetail: "USC Village rideshare zone",
    dropoffDetail: "LAX Terminal 1",
    departureAt: "2026-05-12T06:15:00.000-07:00",
    departureWindowMinutes: 10,
    targetSeats: 4,
    minSeatsToBook: 3,
    maxSeats: 4,
    estimatedTotalFareCents: cents(74),
    approvedMaxTotalFareCents: cents(90),
    currency: "USD",
    ridepodFeeCents: cents(2),
    providerPolicy: null,
    cancellationPolicyId: "standard",
    lockDeadlineAt: "2026-05-11T20:00:00.000-07:00",
    bookingDeadlineAt: "2026-05-12T05:45:00.000-07:00",
    chatUnlockedAt: "2026-05-11T20:05:00.000-07:00",
    detailsUnlockedAt: "2026-05-11T20:05:00.000-07:00",
    hostReplacementStartedAt: null,
    originalHostUserId: null,
    replacementHostUserId: null,
    members: [
      member("u1", "HOST", { podId: "settlement-complete-demo", id: "pm-settlement-complete-demo-u1", memberState: "COMPLETED", paymentState: "CAPTURED", finalChargeCents: cents(24) }),
      member("u6", "RIDER", { podId: "settlement-complete-demo", id: "pm-settlement-complete-demo-u6", memberState: "COMPLETED", paymentState: "CAPTURED", finalChargeCents: cents(24) }),
      member("u7", "RIDER", { podId: "settlement-complete-demo", id: "pm-settlement-complete-demo-u7", memberState: "COMPLETED", paymentState: "CAPTURED", finalChargeCents: cents(24) }),
      member("u4", "RIDER", { podId: "settlement-complete-demo", id: "pm-settlement-complete-demo-u4", memberState: "COMPLETED", paymentState: "CAPTURED", finalChargeCents: cents(24) }),
    ],
    quotes: [
      {
        id: "quote-settlement-complete-demo-1",
        podId: "settlement-complete-demo",
        hostUserId: "u1",
        providerName: "UBER",
        vehicleClass: "XL",
        quotedFareCents: cents(82),
        currency: "USD",
        routeSummary: "USC to LAX",
        screenshotFileUrl: "mock://quote/settlement-complete-demo.png",
        screenshotFileId: "mock-file-settlement-quote",
        submittedAt: now,
        reviewState: "AUTO_APPROVED",
        reviewedByAdminId: null,
        adminNotes: null,
        isFresh: true,
        expiresAt: null,
      },
    ],
    receipts: [
      {
        id: "receipt-settlement-complete-demo-1",
        podId: "settlement-complete-demo",
        hostUserId: "u1",
        providerName: "UBER",
        vehicleClass: "XL",
        externalTripReferenceHash: null,
        receiptFileUrl: "mock://receipt/settlement-complete-demo.png",
        receiptFileId: "mock-file-settlement-receipt",
        fareTotalCents: cents(88),
        baseFareCents: cents(74),
        taxesCents: null,
        tollsCents: cents(6),
        feesCents: null,
        tipCents: cents(8),
        currency: "USD",
        rideStartedAt: "2026-05-12T06:20:00.000-07:00",
        rideCompletedAt: "2026-05-12T07:05:00.000-07:00",
        submittedAt: now,
        verificationState: "VERIFIED",
        reviewedByAdminId: "admin-demo",
        rejectionReason: null,
        fraudScore: null,
        createdAt: now,
        updatedAt: now,
      },
    ],
    adminReviewRequired: false,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockAuditEvents: AuditEvent[] = [];
export const mockRiskFlags: RiskFlag[] = [];
export const mockSettlements: Settlement[] = [];
export const mockHostReimbursements: HostReimbursement[] = [];
export const mockPaymentIntents: RidePodPaymentIntent[] = [];
export const mockProcessedStripeWebhookEvents: ProcessedStripeWebhookEvent[] = [];

export function getProtectedUser(userId: string) {
  return protectedUsers.find((user) => user.id === userId) ?? protectedUsers[0];
}

export function getProtectedPod(podId: string) {
  return protectedPods.find((pod) => pod.id === podId) ?? null;
}

export function getProtectedPodOrFallback(podId: string) {
  return getProtectedPod(podId) ?? protectedPods[0];
}

export function getHostBookingSummary(podId: string) {
  const pod = getProtectedPodOrFallback(podId);
  const permission = canHostBook(pod.replacementHostUserId ?? pod.hostUserId, pod);
  const snapshot = getMoneySafetySnapshot(pod);

  return { pod, permission, snapshot };
}

export function getMockSettlementPreview(podId: string) {
  const pod = getProtectedPodOrFallback(podId);
  const receipt = {
    id: `receipt-${pod.id}-preview`,
    podId: pod.id,
    hostUserId: pod.hostUserId,
    providerName: "UBER" as const,
    vehicleClass: "Large Ride",
    externalTripReferenceHash: null,
    receiptFileUrl: "mock://receipt/usc-lax-001.png",
    receiptFileId: "mock-file-receipt-usc-lax-001",
    fareTotalCents: cents(87.45),
    baseFareCents: cents(72.4),
    taxesCents: null,
    tollsCents: cents(6.25),
    feesCents: null,
    tipCents: cents(8.8),
    currency: "USD",
    rideStartedAt: null,
    rideCompletedAt: null,
    submittedAt: now,
    verificationState: "VERIFIED" as const,
    reviewedByAdminId: "admin-demo",
    rejectionReason: null,
    fraudScore: null,
    createdAt: now,
    updatedAt: now,
  };

  return calculateSettlement(
    {
      ...pod,
      members: pod.members.map((podMember) => ({
        ...podMember,
        memberState: "COMPLETED" as const,
        paymentState: "CAPTURED" as const,
      })),
      receipts: [receipt],
    },
    receipt,
  );
}
