import {
  calculateSettlement,
  canHostBook,
  cents,
  getMoneySafetySnapshot,
  type AuditEvent,
  type HostReimbursement,
  type ProtectedPod,
  type ProtectedPodMember,
  type ProtectedUser,
  type RiskFlag,
  type Settlement,
} from "@/lib/money-safety";

const now = "2026-05-13T12:00:00.000Z";

export const protectedUsers: ProtectedUser[] = [
  {
    id: "u1",
    name: "Maya Chen",
    email: "maya@example.com",
    phone: "+12135550101",
    genderIdentity: "FEMALE",
    genderVerifiedAt: "2024-09-01T10:00:00.000Z",
    verificationStatus: "ID_VERIFIED",
    communityId: "usc",
    trustScore: 4.9,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 0,
    riskStatus: "NORMAL",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u2",
    name: "Andre Lee",
    email: "andre@example.com",
    phone: "+12135550102",
    genderIdentity: "MALE",
    genderVerifiedAt: "2024-09-01T10:00:00.000Z",
    verificationStatus: "PHONE_VERIFIED",
    communityId: "usc",
    trustScore: 4.6,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 0,
    riskStatus: "NORMAL",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u3",
    name: "Priya Shah",
    email: "priya@example.com",
    phone: "+12135550103",
    genderIdentity: "FEMALE",
    genderVerifiedAt: null,
    verificationStatus: "EMAIL_VERIFIED",
    communityId: "usc",
    trustScore: 4.4,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 0,
    riskStatus: "NORMAL",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u6",
    name: "Jordan Lee",
    email: "jordan@example.com",
    phone: "+12135550106",
    genderIdentity: "NON_BINARY",
    genderVerifiedAt: "2024-09-01T10:00:00.000Z",
    verificationStatus: "COMMUNITY_VERIFIED",
    communityId: "usc",
    trustScore: 4.8,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 0,
    riskStatus: "NORMAL",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u7",
    name: "Alex Kim",
    email: "alex@example.com",
    phone: "+12135550107",
    genderIdentity: "PREFER_NOT_TO_SAY",
    genderVerifiedAt: null,
    verificationStatus: "PHONE_VERIFIED",
    communityId: "usc",
    trustScore: 4.7,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 0,
    riskStatus: "NORMAL",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "low-trust",
    name: "Low Trust Rider",
    email: "low@example.com",
    phone: "+12135550108",
    genderIdentity: "FEMALE",
    genderVerifiedAt: "2024-09-01T10:00:00.000Z",
    verificationStatus: "PHONE_VERIFIED",
    communityId: "usc",
    trustScore: 3.9,
    noShowCount: 1,
    lateCancelCount: 1,
    safetyReportCount: 0,
    riskStatus: "WATCH",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "unknown-gender",
    name: "Unknown Gender Rider",
    email: "unknown@example.com",
    phone: "+12135550109",
    genderIdentity: "UNKNOWN",
    genderVerifiedAt: null,
    verificationStatus: "PHONE_VERIFIED",
    communityId: "usc",
    trustScore: 4.7,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 0,
    riskStatus: "NORMAL",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "wrong-community",
    name: "Wrong Community Rider",
    email: "wrong-community@example.com",
    phone: "+12135550110",
    genderIdentity: "FEMALE",
    genderVerifiedAt: "2024-09-01T10:00:00.000Z",
    verificationStatus: "COMMUNITY_VERIFIED",
    communityId: "other",
    trustScore: 4.8,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 0,
    riskStatus: "NORMAL",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "suspended",
    name: "Suspended Rider",
    email: "suspended@example.com",
    phone: "+12135550111",
    genderIdentity: "FEMALE",
    genderVerifiedAt: "2024-09-01T10:00:00.000Z",
    verificationStatus: "ID_VERIFIED",
    communityId: "usc",
    trustScore: 4.9,
    noShowCount: 0,
    lateCancelCount: 0,
    safetyReportCount: 2,
    riskStatus: "SUSPENDED",
    stripeCustomerId: null,
    stripeConnectAccountId: null,
    payoutsEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
];

function member(
  userId: string,
  role: ProtectedPodMember["role"],
  overrides: Partial<ProtectedPodMember> = {},
): ProtectedPodMember {
  return {
    id: `pm-usc-lax-001-${userId}`,
    podId: "usc-lax-001",
    userId,
    role,
    memberState: "CONFIRMED",
    paymentState: "AUTHORIZED",
    seatCount: 1,
    maxChargeCents: cents(24.5),
    estimatedShareCents: cents(18.5),
    finalChargeCents: null,
    platformFeeCents: cents(2),
    cancellationLiabilityCents: null,
    noShowLiabilityCents: null,
    joinedAt: "2026-05-11T10:00:00.000Z",
    lockedAt: "2026-05-13T02:00:00.000Z",
    canceledAt: null,
    cancelReason: null,
    checkinState: "NOT_CHECKED_IN",
    trustDelta: null,
    eligibilityPassed: true,
    createdAt: "2026-05-11T10:00:00.000Z",
    updatedAt: now,
    ...overrides,
  };
}

export const protectedPods: ProtectedPod[] = [
  {
    id: "usc-lax-001",
    hostUserId: "u1",
    lifecycleState: "HOST_CAN_BOOK",
    bookingState: "CAN_BOOK",
    genderMode: "MIXED",
    accessMode: "VERIFIED_ONLY",
    inviteCode: "USC-LAX-MAY14",
    communityId: "usc",
    minTrustScore: null,
    originGeneral: "USC",
    destinationGeneral: "LAX",
    pickupDetail: "USC - Leavey Library rideshare pickup zone",
    dropoffDetail: "LAX - Terminal 1 departures level",
    departureAt: "2026-05-14T07:30:00.000-07:00",
    departureWindowMinutes: 15,
    targetSeats: 4,
    minSeatsToBook: 3,
    maxSeats: 4,
    estimatedTotalFareCents: cents(74),
    approvedMaxTotalFareCents: cents(90),
    currency: "USD",
    ridepodFeeCents: cents(2),
    providerPolicy: "Host books under approved max fare. Everyone pays their share.",
    cancellationPolicyId: "standard-airport",
    lockDeadlineAt: "2026-05-13T20:00:00.000-07:00",
    bookingDeadlineAt: "2026-05-14T07:00:00.000-07:00",
    chatUnlockedAt: "2026-05-13T20:02:00.000-07:00",
    detailsUnlockedAt: "2026-05-13T20:02:00.000-07:00",
    hostReplacementStartedAt: null,
    originalHostUserId: null,
    replacementHostUserId: null,
    members: [member("u1", "HOST"), member("u6", "RIDER"), member("u7", "RIDER")],
    quotes: [
      {
        id: "quote-usc-lax-001-1",
        podId: "usc-lax-001",
        hostUserId: "u1",
        providerName: "UBER",
        vehicleClass: "Large Ride",
        quotedFareCents: cents(82.4),
        currency: "USD",
        routeSummary: "USC to LAX",
        screenshotFileUrl: "mock://quote/usc-lax-001.png",
        screenshotFileId: "mock-file-quote-usc-lax-001",
        submittedAt: "2026-05-13T19:45:00.000-07:00",
        reviewState: "AUTO_APPROVED",
        reviewedByAdminId: null,
        adminNotes: null,
        isFresh: true,
        expiresAt: "2026-05-14T07:00:00.000-07:00",
      },
    ],
    receipts: [],
    adminReviewRequired: false,
    higherMaxApprovedCents: null,
    createdAt: "2026-05-11T10:00:00.000Z",
    updatedAt: now,
  },
  {
    id: "women-only-demo",
    hostUserId: "u1",
    lifecycleState: "FORMING",
    bookingState: "QUOTE_ALLOWED",
    genderMode: "WOMEN_ONLY",
    accessMode: "VERIFIED_ONLY",
    inviteCode: null,
    communityId: "usc",
    minTrustScore: null,
    originGeneral: "USC",
    destinationGeneral: "LAX",
    pickupDetail: null,
    dropoffDetail: null,
    departureAt: "2026-05-14T20:30:00.000-07:00",
    departureWindowMinutes: 10,
    targetSeats: 3,
    minSeatsToBook: 2,
    maxSeats: 3,
    estimatedTotalFareCents: cents(60),
    approvedMaxTotalFareCents: cents(75),
    currency: "USD",
    ridepodFeeCents: cents(2),
    providerPolicy: null,
    cancellationPolicyId: "standard",
    lockDeadlineAt: null,
    bookingDeadlineAt: null,
    chatUnlockedAt: null,
    detailsUnlockedAt: null,
    hostReplacementStartedAt: null,
    originalHostUserId: null,
    replacementHostUserId: null,
    members: [member("u1", "HOST", { podId: "women-only-demo", id: "pm-women-only-demo-u1" })],
    quotes: [],
    receipts: [],
    adminReviewRequired: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "mixed-open-demo",
    hostUserId: "u1",
    lifecycleState: "FORMING",
    bookingState: "QUOTE_ALLOWED",
    genderMode: "MIXED",
    accessMode: "OPEN",
    inviteCode: null,
    communityId: null,
    minTrustScore: null,
    originGeneral: "Downtown",
    destinationGeneral: "Airport",
    pickupDetail: null,
    dropoffDetail: null,
    departureAt: "2026-05-15T08:00:00.000-07:00",
    departureWindowMinutes: 15,
    targetSeats: 4,
    minSeatsToBook: 2,
    maxSeats: 4,
    estimatedTotalFareCents: cents(80),
    approvedMaxTotalFareCents: cents(96),
    currency: "USD",
    ridepodFeeCents: cents(2),
    providerPolicy: null,
    cancellationPolicyId: "standard",
    lockDeadlineAt: null,
    bookingDeadlineAt: null,
    chatUnlockedAt: null,
    detailsUnlockedAt: null,
    hostReplacementStartedAt: null,
    originalHostUserId: null,
    replacementHostUserId: null,
    members: [member("u1", "HOST", { podId: "mixed-open-demo", id: "pm-mixed-open-demo-u1" })],
    quotes: [],
    receipts: [],
    adminReviewRequired: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "community-only-demo",
    hostUserId: "u1",
    lifecycleState: "FORMING",
    bookingState: "QUOTE_ALLOWED",
    genderMode: "MIXED",
    accessMode: "COMMUNITY_ONLY",
    inviteCode: null,
    communityId: "usc",
    minTrustScore: null,
    originGeneral: "USC",
    destinationGeneral: "LAX",
    pickupDetail: null,
    dropoffDetail: null,
    departureAt: "2026-05-16T08:00:00.000-07:00",
    departureWindowMinutes: 15,
    targetSeats: 4,
    minSeatsToBook: 2,
    maxSeats: 4,
    estimatedTotalFareCents: cents(80),
    approvedMaxTotalFareCents: cents(96),
    currency: "USD",
    ridepodFeeCents: cents(2),
    providerPolicy: null,
    cancellationPolicyId: "standard",
    lockDeadlineAt: null,
    bookingDeadlineAt: null,
    chatUnlockedAt: null,
    detailsUnlockedAt: null,
    hostReplacementStartedAt: null,
    originalHostUserId: null,
    replacementHostUserId: null,
    members: [member("u1", "HOST", { podId: "community-only-demo", id: "pm-community-only-demo-u1" })],
    quotes: [],
    receipts: [],
    adminReviewRequired: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "high-trust-demo",
    hostUserId: "u1",
    lifecycleState: "FORMING",
    bookingState: "QUOTE_ALLOWED",
    genderMode: "MIXED",
    accessMode: "HIGH_TRUST_ONLY",
    inviteCode: null,
    communityId: null,
    minTrustScore: 4.5,
    originGeneral: "USC",
    destinationGeneral: "LAX",
    pickupDetail: null,
    dropoffDetail: null,
    departureAt: "2026-05-17T08:00:00.000-07:00",
    departureWindowMinutes: 15,
    targetSeats: 4,
    minSeatsToBook: 2,
    maxSeats: 4,
    estimatedTotalFareCents: cents(80),
    approvedMaxTotalFareCents: cents(96),
    currency: "USD",
    ridepodFeeCents: cents(2),
    providerPolicy: null,
    cancellationPolicyId: "standard",
    lockDeadlineAt: null,
    bookingDeadlineAt: null,
    chatUnlockedAt: null,
    detailsUnlockedAt: null,
    hostReplacementStartedAt: null,
    originalHostUserId: null,
    replacementHostUserId: null,
    members: [member("u1", "HOST", { podId: "high-trust-demo", id: "pm-high-trust-demo-u1" })],
    quotes: [],
    receipts: [],
    adminReviewRequired: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "invite-only-demo",
    hostUserId: "u1",
    lifecycleState: "FORMING",
    bookingState: "QUOTE_ALLOWED",
    genderMode: "MIXED",
    accessMode: "INVITE_ONLY",
    inviteCode: "INVITE-123",
    communityId: null,
    minTrustScore: null,
    originGeneral: "USC",
    destinationGeneral: "LAX",
    pickupDetail: null,
    dropoffDetail: null,
    departureAt: "2026-05-18T08:00:00.000-07:00",
    departureWindowMinutes: 15,
    targetSeats: 4,
    minSeatsToBook: 2,
    maxSeats: 4,
    estimatedTotalFareCents: cents(80),
    approvedMaxTotalFareCents: cents(96),
    currency: "USD",
    ridepodFeeCents: cents(2),
    providerPolicy: null,
    cancellationPolicyId: "standard",
    lockDeadlineAt: null,
    bookingDeadlineAt: null,
    chatUnlockedAt: null,
    detailsUnlockedAt: null,
    hostReplacementStartedAt: null,
    originalHostUserId: null,
    replacementHostUserId: null,
    members: [member("u1", "HOST", { podId: "invite-only-demo", id: "pm-invite-only-demo-u1" })],
    quotes: [],
    receipts: [],
    adminReviewRequired: false,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockAuditEvents: AuditEvent[] = [];
export const mockRiskFlags: RiskFlag[] = [];
export const mockSettlements: Settlement[] = [];
export const mockHostReimbursements: HostReimbursement[] = [];

export function getProtectedUser(userId: string) {
  return protectedUsers.find((user) => user.id === userId) ?? protectedUsers[0];
}

export function getProtectedPod(podId: string) {
  return protectedPods.find((pod) => pod.id === podId) ?? null;
}

export function getProtectedPodOrFallback(podId: string) {
  return getProtectedPod(podId) ?? protectedPods[0];
}

export function getHostBookingSummary(podId: string) {
  const pod = getProtectedPodOrFallback(podId);
  const permission = canHostBook(pod.replacementHostUserId ?? pod.hostUserId, pod);
  const snapshot = getMoneySafetySnapshot(pod);

  return { pod, permission, snapshot };
}

export function getMockSettlementPreview(podId: string) {
  const pod = getProtectedPodOrFallback(podId);
  const receipt = {
    id: `receipt-${pod.id}-preview`,
    podId: pod.id,
    hostUserId: pod.hostUserId,
    providerName: "UBER" as const,
    vehicleClass: "Large Ride",
    externalTripReferenceHash: null,
    receiptFileUrl: "mock://receipt/usc-lax-001.png",
    receiptFileId: "mock-file-receipt-usc-lax-001",
    fareTotalCents: cents(87.45),
    baseFareCents: cents(72.4),
    taxesCents: null,
    tollsCents: cents(6.25),
    feesCents: null,
    tipCents: cents(8.8),
    currency: "USD",
    rideStartedAt: null,
    rideCompletedAt: null,
    submittedAt: now,
    verificationState: "VERIFIED" as const,
    reviewedByAdminId: "admin-demo",
    rejectionReason: null,
    fraudScore: null,
    createdAt: now,
    updatedAt: now,
  };

  return calculateSettlement(
    {
      ...pod,
      members: pod.members.map((podMember) => ({
        ...podMember,
        memberState: "COMPLETED" as const,
        paymentState: "CAPTURED" as const,
      })),
      receipts: [receipt],
    },
    receipt,
  );
}
